# Generated by Django 5.1.2 on 2024-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
