# Generated by Django 5.1.2 on 2024-11-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('business', 'Business')], default='savings', max_length=20),
        ),
    ]
